# Generated by Django 5.0.7 on 2024-07-21 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.CharField(max_length=16, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='create_time',
            field=models.DateField(verbose_name='入职日期'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffmanage.department', verbose_name='所属部门'),
        ),
    ]
