# Generated by Django 5.0.7 on 2024-07-28 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanage', '0004_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, '紧急'), (2, '重要'), (3, '普通')], default=3, verbose_name='任务级别')),
                ('title', models.CharField(max_length=64, verbose_name='任务标题')),
                ('detail', models.TextField(verbose_name='任务详情')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffmanage.admin', verbose_name='任务负责人')),
            ],
        ),
    ]
