# Generated by Django 5.0.7 on 2024-07-28 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanage', '0005_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=64, verbose_name='订单号')),
                ('title', models.CharField(max_length=32, verbose_name='产品名称')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('count', models.IntegerField(default=1, verbose_name='订购数量')),
                ('status', models.SmallIntegerField(choices=[(0, '待支付'), (1, '已支付')], default=0, verbose_name='订单状态')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffmanage.admin', verbose_name='订单管理人')),
            ],
        ),
    ]
