# Generated by Django 5.0.7 on 2024-07-28 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffmanage', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='匿名用户', max_length=32, verbose_name='雇主姓名'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffmanage.employee', verbose_name='订单负责人'),
        ),
    ]
